### ISSUE TITLE
Waste Collector job's leads to Product Dealer job.

### ISSUE THREAD

**Issue by JorgeLopez69** [oneOCT3T/SARPbugs#13]
So, when you /jobhelp and go to Waste Collector's Job and 'Find Job', the checkpoint that pops up on your minimap actually leads to Product Dealers job. I have tested this bug myself on test server including the main server. This is really a bug and needs fixing.

Evidence:

http://imgur.com/uufNBdF
http://imgur.com/8Jnc0Ut
http://imgur.com/r6fZbTO

**Comment by oneOCT3T** [comment]
Fixed, thanks for that!
