### ISSUE TITLE
Police sirens/lights bug

### ISSUE THREAD

**Issue by Melancani** [oneOCT3T/SARPbugs#14]
Upon /v spawn owned cars sometimes spawn with PD sirens/lights. When re-spawned, the siren disappears.

Evidence: 

https://i.imgur.com/CyuPYmi.jpg
https://i.imgur.com/Ic4ovt7.jpg

**Comment by Sparke00** [comment]
It due to someone /siren'ing and neglecting to take it off and it sticks to the vehicle ID. It'll be fixed on a GMX and I'll fix it in the script as well to avoid it happening again.

**Comment by oneOCT3T** [comment]
Was this the fix?
`	if(SirenObject[vehicleid])	//destroy siren
	{
		DestroyDynamicObjectEx(SirenObject[vehicleid]);
		Siren[vehicleid] = 0;
		SirenObject[vehicleid] = 0;
	}`
@OnDestroyVehicle
@Sparke00

**Comment by Sparke00** [comment]
@oneOCT3T Not sure. I guess pending testers to fix?

**Comment by TGoldenB** [comment]
Fixed, also tested.
