### ISSUE TITLE
Custom plate bug

### ISSUE THREAD

**Issue by Melancani** [oneOCT3T/SARPbugs#19]
**[Bug Type (Glitch, Typography or Other.)]**
Glitch

**[Describe the bug, explain how it is caused, and what it does.]**
If entering anything in the field for a license plate and afterwards pressing cancel it will still charge you the 100k.

**[Is this bug restricted to certain factions, groups, or jobs?]**
No

**[Is the bug on the beta server, the main server, or both?]**
Main

**[Proof]**
http://i.imgur.com/8Se93Dz.jpg
http://i.imgur.com/48zfjgm.jpg

**Comment by TGoldenB** [comment]
Fixed.
