### ISSUE TITLE
Calling CreateObjects to lift object in LS beach apartment

### ISSUE THREAD

**Issue by TGoldenB** [oneOCT3T/SARPbugs#2]
I don't have to explain it, a GMX can fix but we need a proper solution. Mainly Octet did that script if I am not wrong.  
Request to Octet for checking the issue and fix the bug since it's not for the mapping objects but lift moveable bug(?)

**Comment by Sparke00** [comment]
Pending Jacob/You

**Comment by TGoldenB** [comment]
Should be fixed now.
