### ISSUE TITLE
Radio on bicycles.

### ISSUE THREAD

**Issue by Melancani** [oneOCT3T/SARPbugs#20]
**[Bug Type (Glitch, Typography or Other.)]**
Glitch

**[Describe the bug, explain how it is caused, and what it does.]**
When using /veh to spawn a bike it spawns with a radio stream if the previous vehicle ID had a stream enabled. The stream is carried over from previous vehicle ID

**[Is this bug restricted to certain factions, groups, or jobs?]**
Admin restricted /veh, got a few reports the bug occurring with regular players.

**[Is the bug on the beta server, the main server, or both?]**
Both

**[Evidence]**
http://i.imgur.com/CIC1L9N.jpg

**Comment by TGoldenB** [comment]
Fixed.
