### ISSUE TITLE
Mapping Issue at the Apartments

### ISSUE THREAD

**Issue by SolitudeF** [oneOCT3T/SARPbugs#21]
![sa-mp-177](https://user-images.githubusercontent.com/29804238/27751279-601502ac-5d90-11e7-9e1b-ebd0bb92d7be.png)
![sa-mp-175](https://user-images.githubusercontent.com/29804238/27751280-601d5df8-5d90-11e7-86e2-840b91bbd8ef.png)

This issue still exists. Can this be fixed once and for all? It blocks out the houses in that mapping.

**Comment by TGoldenB** [comment]
@oneOCT3T  Do something?

**Comment by Sparke00** [comment]
@TGoldenB You're the lead mapper?

**Comment by TGoldenB** [comment]
@Sparke00  It's because of @oneOCT3T 's script and I don't want to hand on his script mate.
There no problem from mapping codes but that lift scripting.

**Comment by TGoldenB** [comment]
@oneOCT3T  Please check this, your script beachside_apartment giving this problem.

**Comment by Sparke00** [comment]
@TGoldenB The lift scripting is in SAMP not anything we've done.

**Comment by Sparke00** [comment]
Fixed.
