### ISSUE TITLE
/doorknock can't be heard 

### ISSUE THREAD

**Issue by Melancani** [oneOCT3T/SARPbugs#22]
[Bug Type (Glitch, Typography or Other.)]
Glitch

[Describe the bug, explain how it is caused, and what it does.]
When someone uses /doorknock, the knock doesn't display for the person in the house.

[Is this bug restricted to certain factions, groups, or jobs?]
No.

[Is the bug on the beta server, the main server, or both?]
Main

**Comment by oneOCT3T** [comment]
Fixed. Thanks.
