### ISSUE TITLE
Interior bug.

### ISSUE THREAD

**Issue by Johny909** [oneOCT3T/SARPbugs#25]
- [(Glitch, Typography or Other.]
Other.

Describe the bug, explain how it is caused, and what it does:*
So basically if you own a house with this interior: 
http://imgur.com/a/WxX4L
http://imgur.com/a/yh1ce
http://imgur.com/a/qe2PJ
And you wanna /furniture so it will appear in EVERY house with the specific interior that I showed.
Like the sofa, I've tested 2 houses with this interior, they had the same types of furniture.
Another evidence:
http://imgur.com/a/Ow50s
http://imgur.com/a/HjKUk

Ben can confirm.

**Comment by Sparke00** [comment]
It seems to be a virtual world issue, I'll look into it.

**Comment by Sparke00** [comment]
Will be fixed next update
