### ISSUE TITLE
Invisible vehicle.

### ISSUE THREAD

**Issue by KojiTakamato** [oneOCT3T/SARPbugs#8]
**[Bug Type (Glitch, Typography or Other.)]**
Glitch.

**[Describe the bug, explain how it is caused, and what it does.]**
When someone is TPed inside an interior with an car or bike, the bike and the car will be invisible.

**[Is this bug restricted to certain factions, groups, or jobs?]**
Nope.

**[Is the bug on the beta server, the main server, or both?]**
Both.

OP: (Alaska_Grante's) http://www.gta-sarp.com/forums/showthread.php?249730-Tester-Alaska_Grante-s-Bug-Report&p=1860602&viewfull=1#post1860602

**Comment by TGoldenB** [comment]
@KojiTakamato  I have tested it all the way I can do, no bug found. I need more explanations.
I tried /goto, /gethere and they works fine. /gethere was having a problem I fixed that many days ago.

**Comment by KojiTakamato** [comment]
Try /gotonewbie or /hn, as a helper, and then /hveh inside an interior. I've experienced that more times than I can count.

**Comment by TGoldenB** [comment]
I have fixed it, closed.
